[settings]
legacy_version_file = false

[tools]
jsonnet-tool = "1.15.7"
# Please continue to use `.tool-versions` to specify tools, rather than adding them directly here.

[plugins]
# Use this section to configure the source of any custom mise/asdf plugin
promtool = 'https://gitlab.com/gitlab-com/gl-infra/asdf-promtool.git'
thanos = 'https://gitlab.com/gitlab-com/gl-infra/asdf-promtool.git'
amtool = 'https://gitlab.com/gitlab-com/gl-infra/asdf-promtool.git'
jsonnet-tool = 'https://gitlab.com/gitlab-com/gl-infra/asdf-gl-infra.git'
kubeconform = 'https://github.com/lirlia/asdf-kubeconform.git'
mimirtool = 'https://github.com/asdf-community/asdf-mimirtool'
