---
exclude: ^spec/fixtures/|\.svg$|\.svg$|\.excalidraw$|\.drawio$|reference-architectures/get-hybrid/config|test/lib/shunit2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/google/go-jsonnet
    rev: v0.20.0
    hooks:
      - id: jsonnet-format
        args: [-i, --string-style, s, -n, "2"]

  # pre-commit tasks from common-ci-tasks
  # Documentation available at
  # https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/blob/main/docs/pre-commit.md
  - repo: https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks
    rev: v2.40  # renovate:managed

    hooks:
      - id: shellcheck  # Run shellcheck for changed Shell files
      - id: shfmt  # Run shellcheck for changed Shell files
      - id: update-asdf-version-variables  # Update .gitlab-ci-asdf-versions.yml if .tool-versions has changed

      # - id: gitlint  # Checks your git commit messages for style
      - id: gitleaks  #  Detect hardcoded secrets using Gitleaks
      - id: editorconfig  # Validate text files against .editorconfig
      - id: yamllint  # Validate YAML files using yamllint
      - id: go-fmt  # Run gofmt for changed Go files
      - id: go-imports  # Run go-imports for changed Go files
      - id: go-mod-tidy  # Run go mod tidy for changed Go files
      - id: go-test  # Run go test for the project if any go files have changed
      - id: golangci-lint  # Run golangci-lint for changed Go files
