groups:
- name: Alertmanager
  rules:
  - alert: AlertmanagerNotificationsFailing
    expr: >
      sum by (integration) (
        increase(alertmanager_notifications_failed_total{integration!="webhook", env="ops"}[5m])
      ) > 4
    labels:
      pager: pagerduty
      severity: s1
      alert_type: cause
      type: alertmanager
    annotations:
      title: Alertmanager is failing sending notifications
      runbook: docs/monitoring/alertmanager-notification-failures.md
      description: Alertmanager is seeing errors for the {{$labels.integration}} integration.
  - alert: AlertmanagerWebhookNotificationsFailing
    expr: >
      sum by (integration) (
        increase(alertmanager_notifications_failed_total{integration="webhook", env="ops"}[5m])
      ) > 10
    for: 10m
    labels:
      pager: pagerduty
      severity: s2
      alert_type: cause
      type: alertmanager
    annotations:
      title: Alertmanager is failing sending notifications for the webhook integration
      runbook: docs/monitoring/alertmanager-notification-failures.md
      description: Alertmanager is seeing errors for the webhook integration, check https://console.cloud.google.com/functions/details/us-central1/alertManagerBridge?env=gen1&project=gitlab-infra-automation
